# Generated by Django 5.1.6 on 2025-03-04 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=79)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('old_price', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('image', models.URLField()),
                ('logo', models.CharField(max_length=255)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
    ]
